---
AWSTemplateFormatVersion: '2010-09-09'
Parameters: 
  RootDomainName:
    Description: Domain name for your website (example.com)
    Type: String

Resources:     
  WebReadBucketPolicy: 
    Type: "AWS::S3::BucketPolicy"
    Properties: 
      Bucket: 
        !Ref RootBucket
      PolicyDocument: 
        Statement: 
          - 
            Action: 
              - "s3:GetObject"
            Effect: "Allow"
            Resource: 
              Fn::Join: 
                - ""
                - 
                  - "arn:aws:s3:::"
                  - !Ref RootBucket
                  - "/*"
            Principal: "*"            
  RootBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: PublicRead      
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
  WWWBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: BucketOwnerFullControl
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref RootBucket
  ApiContentBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: BucketOwnerFullControl

Outputs:
  RootDomainName:
    Value: !GetAtt RootBucket.DomainName
    Description: Domain name for for website hosted on S3
    Export:
      Name: HelipadRootDomainName
  RootBucketName:
    Value: !Ref RootBucket
    Description: Domain name for for website hosted on S3
    Export:
      Name: HelipadRootBucketName
  WWWDomainName:
    Value: !GetAtt WWWBucket.DomainName
    Description: Domain name for for www. subdomain name website hosted on S3
    Export:
      Name: HelipadWWWDomainName
  ApiBucketName:
    Value: !Ref ApiContentBucket
    Description: Domain name for for ApiContentBucket
    Export:
      Name: HelipadApiContentBucketDomainName