---
AWSTemplateFormatVersion: '2010-09-09'
Parameters: 
  HelipadDynamoDBTableReads:
    Description: DynamoDB table ReadCapacityUnits this will be how you are charged on DynamoDB
    Default: 1
    Type: Number
  HelipadDynamoDBTableWrites:
    Description: DynamoDB table WriteCapacityUnits this will be how you are charged on DynamoDB
    Type: Number
    Default: 1
Resources:
  HelipadDynamoDBTable: 
    Type: "AWS::DynamoDB::Table"
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "user_id"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "user_id"
          KeyType: "HASH"
      ProvisionedThroughput: 
        ReadCapacityUnits: !Ref HelipadDynamoDBTableReads
        WriteCapacityUnits: !Ref HelipadDynamoDBTableWrites
      TableName: "HelipadUserTable"  