---
AWSTemplateFormatVersion: '2010-09-09'
  
Resources:
  HelipadRestAPI: 
    Type: "AWS::ApiGateway::RestApi"
    Properties: 
      BodyS3Location: 
        Key: swagger.yaml
        Bucket: !ImportValue HelipadApiContentBucketDomainName      
      Description: "Helipad super simple API"
      Name: "HelipadRestAPI"

  