# this is an example of the Helipad API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Helipad
  description: Heliad landing page API
  version: "1.0.0"
schemes:
  - https
  - http
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
  /users/{user_id}:
    put:
      summary: Create user
      description: |
        Creates the new user.
      parameters:
        - name: user_id
          in: path
          description: ID of user to create
          required: true
          type: string
      responses:
        200:
          description: Successful response
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
